# Generated by Django 5.2.4 on 2025-07-10 12:24

import deliveries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='from_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Откуда'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='log_file',
            field=models.FileField(blank=True, null=True, upload_to='log_files/', validators=[deliveries.models.validate_csv], verbose_name='Файл логирования (CSV)'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='media_files/', validators=[deliveries.models.validate_pdf], verbose_name='Медиафайл (PDF)'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='to_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Куда'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='travel_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Время в пути'),
        ),
    ]
