# Generated by Django 5.2.4 on 2025-07-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_delivery_comment_delivery_from_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
