# Generated by Django 5.2.4 on 2025-07-10 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_techstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='status',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='tech_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deliveries.techstate', verbose_name='Тех. состояние'),
        ),
    ]
