# Generated by Django 5.2.4 on 2025-07-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_remove_delivery_status_alter_delivery_tech_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='travel_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время в пути'),
        ),
    ]
