# Generated by Django 5.2.4 on 2025-07-10 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_delivery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='delivery',
            name='tech_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deliveries.techstatus', verbose_name='Тех. состояние'),
        ),
        migrations.DeleteModel(
            name='TechState',
        ),
    ]
