# Generated by Django 5.2.4 on 2025-07-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_techstatus_alter_delivery_tech_state_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechStatus',
            new_name='TechState',
        ),
    ]
